# Hardware configuration for flatmate.
# Generated by nixos-generate-config, adapted to dendritic format.
{
  flake.modules.nixos.flatmate = {
    config,
    lib,
    ...
  }: {
    hardware.enableRedistributableFirmware = true;

    boot = {
      initrd = {
        availableKernelModules = ["xhci_pci" "nvme"];
        kernelModules = [];
      };
      kernelModules = ["kvm-intel"];
      extraModulePackages = [];
    };

    networking.useDHCP = lib.mkDefault true;

    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
