# Hardware configuration for endgame.
# Generated by nixos-generate-config, adapted to dendritic format.
{
  flake.modules.nixos.endgame = {
    config,
    lib,
    ...
  }: {
    hardware.enableRedistributableFirmware = true;

    boot = {
      initrd = {
        availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "hid"];
        kernelModules = ["amdgpu"];
      };
      kernelModules = ["kvm-amd" "amdgpu"];
      extraModulePackages = [];
    };

    networking.useDHCP = lib.mkDefault true;

    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
