# Hardware configuration for spectre.
# Generated by nixos-generate-config, adapted to dendritic format.
{
  flake.modules.nixos.spectre = {
    config,
    lib,
    ...
  }: {
    hardware.enableRedistributableFirmware = true;

    boot = {
      initrd = {
        availableKernelModules = [
          "xhci_pci"
          "ahci"
          "sr_mod"
          "virtio_pci"
          "virtio_blk"
        ];
        kernelModules = ["amdgpu"];
      };
      kernelModules = [];
      extraModulePackages = [];
    };

    networking.useDHCP = lib.mkDefault true;

    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
